feat(slidesdown): add update command option

diff --git a/slidesdown b/slidesdown
--- a/slidesdown
+++ b/slidesdown
@@ -94,18 +94,106 @@ open_url() {
 }
 
 main() {
-	local DOCKER="$1"
-	local EXPORT="$2"
-	local RESOLUTION="$3"
-	local NO_OPEN="$4"
-	local PORT="$5"
-	local IMAGE="$6"
-	local SERVICE="$7"
+	local SCRIPT_NAME="${1}"
+	shift
+
+	local TEMP
+	TEMP=$(getopt -o 'hednup:i:r:' --long 'help,export,docker,no-open,update,port:,image:,resolution:' -- "$@")
+
+	# Note the quotes around "$TEMP": they are essential!
+	eval set -- "$TEMP"
+	unset TEMP
+
+	while true; do
+		case "$1" in
+		'-h' | '--help')
+			echo "USAGE: $(basename "${0}") [OPTIONS] [FILENAME]"
+			echo "OPTIONS (option can also be set via environment variable):"
+			echo -e '  -h|--help\tPrint this usage information'
+			echo -e '  -e|--export\tExport slideshow as PDF - if exporting from a local docker instance repeat the options that were used to start the service when using this option (env EXPORT)'
+			echo -e '  -r|--resolution\tExport resolution (default: 2560x144, env RESOLUTION)'
+			echo -e '  -d|--docker\tRun slideshow service locally via docker (default: is to run a local http server via Python3 and connect to an online service, env DOCKER)'
+			echo -e '  -i|--image\tUse docker image (default: jceb/slidesdown:latest, env IMAGE)'
+			echo -e '  -p|--port\tOpen slideshow service at port (default: 3000, env PORT)'
+			echo -e '  -s|--service\tConnect to online service (default: slidesdown.e-jc.de, env SERVICE)'
+			echo -e '  -n|--no-open\tDo not open browser at the start (env NO_OPEN)'
+			echo -e '  -u|--update\tUpdate slidesdown script (env UPDATE)'
+			echo "FILENAME: default SLIDES.md"
+			echo
+			echo "Attention: only the docker service provides hot-reloading when changes are made to the slideshow!"
+			exit
+			;;
+		'-d' | '--docker')
+			local DOCKER=1
+			shift
+			continue
+			;;
+		'-e' | '--export')
+			local EXPORT=1
+			shift
+			continue
+			;;
+		'-p' | '--port')
+			local PORT="${2}"
+			shift 2
+			continue
+			;;
+		'-i' | '--image')
+			local IMAGE="${2}"
+			shift 2
+			continue
+			;;
+		'-r' | '--resolution')
+			local RESOLUTION="${2}"
+			shift 2
+			continue
+			;;
+		'-s' | '--service')
+			local SERVICE="${2}"
+			shift 2
+			continue
+			;;
+		'-n' | '--no-open')
+			local NO_OPEN=1
+			shift
+			continue
+			;;
+		'-u' | '--update')
+			local UPDATE=1
+			shift
+			continue
+			;;
+		'--')
+			shift
+			break
+			;;
+		*)
+			echo 'Internal error!' >&2
+			exit 1
+			;;
+		esac
+	done
+
+	local DOCKER="${DOCKER:-}"
+	local EXPORT="${EXPORT:-}"
+	local UPDATE="${UPDATE:-}"
+	local NO_OPEN="${NO_OPEN:-}"
+	local PORT="${PORT:-3000}"
+	local IMAGE="${IMAGE:-jceb/slidesdown:latest}"
+	local SERVICE="${SERVICE:-https://slidesdown.e-jc.de}"
+	local RESOLUTION="${RESOLUTION:-2560x1440}"
+
 	local ROOT_DIRECTORY
-	ROOT_DIRECTORY="$(readlink -f "$(dirname "${8}")")/"
+	ROOT_DIRECTORY="$(readlink -f "$(dirname "${1:-SLIDES.md}")")/"
 	local SLIDES
-	SLIDES="$(basename "${8}")"
+	SLIDES="$(basename "${1:-SLIDES.md}")"
 	local URL
+	if [[ -n "${UPDATE}" ]]; then
+		echo "Updating ${SCRIPT_NAME}"
+		curl -sfLo "${SCRIPT_NAME}" "https://raw.githubusercontent.com/jceb/slidesdown/main/slidesdown"
+		echo "Update complete"
+		return
+	fi
 	if [[ -n "${DOCKER}" ]]; then
 		URL="$(compute_url "http://localhost:${PORT}" "slides/${SLIDES}")"
 	else
@@ -114,8 +202,8 @@ main() {
 	if [[ -z "${EXPORT}" ]]; then
 		if [[ -n "${DOCKER}" ]]; then
 			CONTAINER_ID="$(run_docker "${PORT}" "${IMAGE}" "${ROOT_DIRECTORY}" "${SLIDES}")"
-			trap "docker kill '${CONTAINER_ID}'" 1 2 3 15
-			echo "Waiting for container to start"
+			trap "docker kill '${CONTAINER_ID}' >/dev/null" 1 2 3 15
+			echo "Waiting for container to start.."
 			sleep 2
 			echo "Slideshow URL: ${URL}"
 			open_url "${NO_OPEN}" "${URL}"
@@ -131,89 +219,4 @@ main() {
 	fi
 }
 
-TEMP=$(getopt -o 'hednp:i:r:' --long 'help,export,docker,no-open,port:,image:,resolution:' -- "$@")
-
-if [ $? -ne 0 ]; then
-	echo 'Terminating...' >&2
-	exit 1
-fi
-
-# Note the quotes around "$TEMP": they are essential!
-eval set -- "$TEMP"
-unset TEMP
-
-while true; do
-	case "$1" in
-	'-h' | '--help')
-		echo "USAGE: $(basename "${0}") [OPTIONS] [FILENAME]"
-		echo "OPTIONS:"
-		echo -e '  -h|--help\tprint this usage information'
-		echo -e '  -e|--export\texport slideshow as PDF - if exporting from a local docker instance repeat the options that were used to start the service when using this option ($EXPORT)'
-		echo -e '  -r|--resolution\texport resolution (default: 2560x144, $RESOLUTION)'
-		echo -e '  -d|--docker\trun slideshow service locally via docker (default: is to run a local http server via Python3 and connect to an online service, $DOCKER)'
-		echo -e '  -i|--image\tuse docker image (default: jceb/slidesdown:latest, $IMAGE)'
-		echo -e '  -p|--port\topen slideshow service at port (default: 3000, $PORT)'
-		echo -e '  -s|--service\tconnect to online service (default: slidesdown.e-jc.de, $SERVICE)'
-		echo -e '  -n|--no-open\tdo not open browser at the start ($NO_OPEN)'
-		echo "FILENAME: default SLIDES.md"
-		echo
-		echo "Attention: only the docker service provides hot-reloading when changes are made to the slideshow!"
-		exit
-		;;
-	'-d' | '--docker')
-		DOCKER=1
-		shift
-		continue
-		;;
-	'-e' | '--export')
-		EXPORT=1
-		shift
-		continue
-		;;
-	'-p' | '--port')
-		PORT="${2}"
-		shift 2
-		continue
-		;;
-	'-i' | '--image')
-		IMAGE="${2}"
-		shift 2
-		continue
-		;;
-	'-r' | '--resolution')
-		RESOLUTION="${2}"
-		shift 2
-		continue
-		;;
-	'-s' | '--service')
-		SERVICE="${2}"
-		shift 2
-		continue
-		;;
-	'-n' | '--no-open')
-		NO_OPEN=1
-		shift
-		continue
-		;;
-	'--')
-		shift
-		break
-		;;
-	*)
-		echo 'Internal error!' >&2
-		exit 1
-		;;
-	esac
-done
-
-DOCKER="${DOCKER:-}"
-EXPORT="${EXPORT:-}"
-NO_OPEN="${NO_OPEN:-}"
-PORT="${PORT:-3000}"
-IMAGE="${IMAGE:-jceb/slidesdown:latest}"
-SERVICE="${SERVICE:-https://slidesdown.e-jc.de}"
-RESOLUTION="${RESOLUTION:-2560x1440}"
-
-SLIDES="${1:-${SLIDES:-SLIDES.md}}"
-
-main "${DOCKER}" "${EXPORT}" "${RESOLUTION}" "${NO_OPEN}" "${PORT}" "${IMAGE}" "${SERVICE}" "${SLIDES}"
+main "$(readlink -f "$0")" "${@}"
